# This file contains configuration details of the Dysart application server.
# It is generally accessed through the `config` variable in the `toplevel.conf`
# module. You should edit this file to suit your deployment.

# Dysart server options If you are running Mongodb as a daemon or Windows
# service, replace the `start_db` option--which starts a database server as a
# subprocess--with `db_discover`, which finds a running mongodb process.
options:
  - start_db

# The address of the dysart server
server_host: '127.0.0.1'

# The port bound by the Dysart server.
server_port: 31415

# The machine the mongodb database runs on
db_host: localhost

# The port that the mongodb database listens on
db_port: 55455

# Name of the mongodb database to use.
default_db: debug_data

# The machine running the Labber instance
labber_host: localhost

logfile_name: .dysart.log

# Path to the root of the project
dys_path: ~/equs/QMIT/dysart

# Where logfiles go
labber_data_dir: ~/equs/QMIT/dysart/debug_data/labber

# These are the projects known to the server. I'm not sure about keeping this
# in the database--for now, they'll live in configuration.
projects:
  demo: ~/equs/QMIT/dysart/dysart/equs_std/equs_demo.yaml

# Add your token here!
tokens:
  - "a8072dffff65e5669c3142c21632381e25307bc0"
